DROP TRIGGER loc_trigger;
DROP TRIGGER school_trigger;
DROP SEQUENCE loc_sequence;
DROP SEQUENCE school_sequence;
DROP TABLE Has;
DROP TABLE Tag;
ALTER TABLE Album DROP CONSTRAINT album_ref_photo;
ALTER TABLE Photo DROP CONSTRAINT photo_ref_album;
DROP TABLE Album;
DROP TABLE Photo;
DROP TABLE Friends;
DROP TABLE Attended;
DROP TABLE Participant;
DROP TABLE Event;
DROP TABLE Users;
DROP TABLE Location;
DROP TABLE School;
