INSERT INTO Location (city, state, country)
    SELECT DISTINCT
        HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY
    FROM PUBLIC_USER_INFORMATION
    UNION
    SELECT DISTINCT
        CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY
    FROM PUBLIC_USER_INFORMATION
    UNION
    SELECT DISTINCT
        EVENT_CITY, EVENT_STATE, EVENT_COUNTRY
    FROM PUBLIC_EVENT_INFORMATION;
